version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development # Use "development" or "production"
    volumes:
      - ./packages/backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development # Use "development" or "production"
    volumes:
      - ./packages/frontend:/app
      - /app/node_modules
